# Generated by Django 2.1.3 on 2018-11-28 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'artist',
            },
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('art_title', models.CharField(max_length=50)),
                ('image', models.TextField()),
                ('isAvailable', models.BooleanField(blank=True)),
                ('artist_id', models.ForeignKey(db_column='artist_id', on_delete=django.db.models.deletion.CASCADE, to='artists.Artist')),
            ],
            options={
                'db_table': 'artwork',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('art_id', models.ForeignKey(db_column='art_id', on_delete=django.db.models.deletion.CASCADE, to='artists.Artwork')),
                ('artist_id', models.ForeignKey(db_column='artist_id', on_delete=django.db.models.deletion.CASCADE, to='artists.Artist')),
                ('customer_id', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, to='artists.Customer')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='order_id',
            field=models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, to='artists.Orders'),
        ),
        migrations.AddField(
            model_name='artist',
            name='art_id',
            field=models.ForeignKey(db_column='art_id', on_delete=django.db.models.deletion.CASCADE, to='artists.Artwork'),
        ),
    ]
