# Generated by Django 2.1.3 on 2018-11-28 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='art_id',
        ),
    ]
