# Generated by Django 2.1.3 on 2018-11-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0005_auto_20181128_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
