# Generated by Django 2.1.3 on 2018-12-01 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0006_auto_20181129_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='artist_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='order_id',
        ),
        migrations.AlterField(
            model_name='orders',
            name='art_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='artist_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='customer_id',
            field=models.CharField(max_length=50),
        ),
    ]
