# Generated by Django 2.1.3 on 2018-12-01 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0007_auto_20181130_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='artist_id',
            field=models.ForeignKey(db_column='artist_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='artists.Artist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='order_id',
            field=models.ForeignKey(db_column='order_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='artists.Orders'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='art_id',
            field=models.ForeignKey(db_column='art_id', on_delete=django.db.models.deletion.CASCADE, to='artists.Artwork'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='artist_id',
            field=models.ForeignKey(db_column='artist_id', on_delete=django.db.models.deletion.CASCADE, to='artists.Artist'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='customer_id',
            field=models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, to='artists.Customer'),
        ),
    ]
